### ISSUE TITLE
Composant datepicker

### ISSUE THREAD

**Issue by stevenMouret** [Etat-Plateforme/rgaa_composants_javascript#10]
Il me semble qu'un tableau de données doit posséder un résumé ainsi qu'un titre.

**Comment by OlivierNourry** [comment]
Bonjour Steven,
Le résumé, c'est uniquement en cas de tableau de données complexe (c'est-à-dire avec fusion de cellules et/ou en-tête qui ne porte pas sur une colonne ou ligne entière).

**Comment by stevenMouret** [comment]
Salut Olivier, oui en effet, le titre reste obligatoire par contre.

**Comment by OlivierNourry** [comment]
Pardon, j'ai répondu un peu vite.
Le tableau n'en est plus un :) du fait du role="grid". A partir de là les recos pour les tableaux ne sont plus applicables. Tu noteras d'ailleurs la présence d'un role="header" qui s'y substitue dans le DP grid.

A noter que ce composant est encore en gestation dans la version courante des ARIA practices: https://github.com/w3c/aria-practices/issues/34

**Comment by stevenMouret** [comment]
Ok merci
